version: "3.7"

services:
  # configure api
  app:
    build:
      context: .
    #    ports:
    #      - "888:5000"
    volumes:
      - ./BACKEND:/app                                   # TODO
      - /app/node_modules
    restart: on-failure
    command: >
      node app.js

  # configure front
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./FRONTEND_BUILD:/usr/share/nginx/html           # TODO
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
