version: "3.7"

services:
  # configure api
  app:
    build:
      context: .
    #    ports:
    #      - "888:5000"
    volumes:
      - ./BACKEND:/app                                   # TODO
      - /app/node_modules
    restart: on-failure
    command: >
      node app.js

  # configure front
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./FRONTEND_BUILD:/usr/share/nginx/html           # TODO
      - ./nginx.conf:/etc/nginx/conf.d/default.conf



#  configure MongoDB
#  db:
#    image: mongo
#    env_file:
#      - .env
#    restart: on-failure
#    ports:
#      - "27018:27017"
#    volumes:
#      - ./mongo-db:/data/db
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
